# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='article.User'),
        ),
        migrations.AlterField(
            model_name='article',
            name='allow_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
