# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170331_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='validate_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
