# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20170331_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
