# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_article_comment_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_comment',
            field=models.BooleanField(default=True),
        ),
    ]
