# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20170408_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
